config/routes.rb
Rails.application.routes.draw do
  root 'firstpage#index'
  
  resource :contacts, only: %i[new create]
  resources :contacts, id: /\d+/, only: %i[edit destroy] do
    post :update
  end
  resource :users, only: %i[new create]
  resources :users, id: /\d+/, only: %i[edit destroy] do
    post :update
  end


  # resource :contact, only: %i[new create] do
  #   collection do
  #     match :confirm, via: %i[post patch]
  #     get :complete
  #   end
  # end


  # get 'contacts/new', to: 'contacts#new'
  # get 'contacts/confirm', to: 'contacts#confirm'
  # get 'contacts/create', to: 'contacts#create'
  # get 'contacts/complete', to: 'contacts#complete'
  get 'firstpage', to: 'firstpage#index'
  get 'firstpagepost', to: 'firstpage#post'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id           :bigint           not null, primary key
#  address      :text
#  company_name :text
#  tel          :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_contacts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  first_name :text
#  last_name  :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
    has_many :contacts, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render(:new)
    else 
      @contact.save
      redirect_to(root_path)
    end
  end

  def edit 
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:contact_id])
    if @contact.update(contact_params)
      redirect_to(root_path)
    else
      render(:edit)
    end
  end

  def complete
  end

  def destroy
    contact = Contact.find(params[:id])
    if contact.present?
      contact.destroy
      redirect_to(root_path)
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:company_name, :address, :tel, :user_id)
  end
end

app/controllers/firstpage_controller.rb
class FirstpageController < ApplicationController
  def index
    @list_users = User.all
    @list_contacts = Contact.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.required(:user).permit(:first_name, :last_name))
    if @user.invalid?
      render(:new)
    else 
      @user.save
      redirect_to(root_path)
    end
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    if @user.update(user_params)
      redirect_to(root_path)
    else
      render(:edit)
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.present?
      user.destroy
      redirect_to(root_path)
    end
  end

  # def alert 
  #   respond_to do |format|
  #     format.js
  #   end
  # end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/firstpage_helper.rb
module FirstpageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/complete.html.slim
h1 Contacts#complete
p Find me in app/views/contacts/complete.html.slim

app/views/contacts/confirm.html.slim
h1 Contacts#confirm
p Find me in app/views/contacts/confirm.html.slim

app/views/contacts/create.html.slim
h1 Contacts#create
p Find me in app/views/contacts/create.html.slim

app/views/contacts/edit.html.slim
= form_for(:contact, url: contact_update_path(@contact)) do |f|
  div.field
    .select
      = f.select(:user_id, User.pluck(:first_name, :id), include_blank: 'Please Select User')
          
  div.field
    = f.label(:address)
    br
    = f.text_area(:address)

  div.field
    = f.label(:company_name)
    br
    = f.text_field(:company_name)

  div.field
    = f.label(:tel)
    br
    = f.telephone_field(:tel)

  div.actions
    = f.submit

app/views/contacts/new.html.slim
= form_for(:contact, url: contacts_path(@contact)) do |f|
  div.field
    .select
      = f.select(:user_id, User.pluck(:first_name, :id), include_blank: 'Please Select User')
          
  div.field
    = f.label(:address)
    br
    = f.text_area(:address)

  div.field
    = f.label(:company_name)
    br
    = f.text_field(:company_name)

  div.field
    = f.label(:tel)
    br
    = f.telephone_field(:tel)

  div.actions
    = f.submit

app/views/firstpage/index.html.slim
h1 Firstpages

span  
  a href="users/new" Create User
span &nbsp;
span  
  a href="contacts/new" Create Contact
      
br
div
  h4 List Users
  - @list_users.each do |user|
    ul
      li 
        span #{user.first_name} #{user.last_name} &nbsp;
        = link_to('Edit', edit_user_path(user)) 
        span &nbsp;
        = link_to('Delete', user_path(user.id), method: :delete, data: { confirm: "Do you want to delete?" })
br
div
  h4 List Contacts
  - @list_contacts.each do |contact|
    ul
      li 
        strong #{contact.user.first_name} #{contact.user.last_name}
        p
        span #{contact.company_name} #{contact.tel} &nbsp;
        = link_to('Edit', edit_contact_path(contact))
        span &nbsp;
        = link_to('Delete', contact_path(contact.id), method: :delete, data: { confirm: "Do you want to delete?" }) 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DockerRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/destroy.js.slim
javascript:
      alert('Delete User Success')

app/views/users/edit.html.slim
h1 = @show_user_id

= form_for(:user, url: user_update_path(@user)) do |f|
  div.field
    = f.label(:first_name)
    br
    = f.text_field(:first_name)

  div.field
    = f.label(:last_name)
    br
    = f.text_field(:last_name)

  div.actions
    = f.submit

app/views/users/new.html.slim
= form_for(:user, url: users_path(@user)) do |f|
  div.field
    = f.label(:first_name)
    br
    = f.text_field(:first_name)

  div.field
    = f.label(:last_name)
    br
    = f.text_field(:last_name)

  div.actions
    = f.submit